directories:
  output: release
  buildResources: build
appId: com.gdesast.certificaciones
productName: Certificaciones
files:
  - filter:
      - dist/Proyecto-Certificaciones/**
      - electron/**
asar: false
mac:
  category: public.app-category.productivity
  target:
    - dmg
    - zip
win:
  target:
    - nsis
    - portable
linux:
  target:
    - AppImage
    - deb
    - rpm
publish: null
extraMetadata:
  main: electron/main.js
electronVersion: 31.7.7
